### ISSUE TITLE
An unknown error occurred.

### ISSUE THREAD

**Issue by davidhellmann** [charliedevelopment/craft3-blockonomicon#1]
![image](https://user-images.githubusercontent.com/764292/36940338-519d1f02-1f41-11e8-91a0-72406747e04b.png)

I've installed it locally and it runs fine. Then I test it on a other machine (same repo) with a DB dump from the first machine and now there is this error. And I can't do anything within the plugin. 

All yellow
![image](https://user-images.githubusercontent.com/764292/36940343-9b505de4-1f41-11e8-86e9-e7ab2d407aaa.png)

**Comment by davidhellmann** [comment]
On some Matrix Fields on the left I get template errors

```
yii\base\ErrorException: Undefined index: name in /Users/dh/___DEV/___Private/xyz.webdevs.www/___dist/vendor/charliedev/blockonomicon/src/controllers/SettingsController.php:128
Stack trace:
#0 /Users/dh/___DEV/___Private/xyz.webdevs.www/___dist/vendor/yiisoft/yii2/base/InlineAction.php(57): charliedev\blockonomicon\controllers\SettingsController->actionEditMatrix()
#1 /Users/dh/___DEV/___Private/xyz.webdevs.www/___dist/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/Users/dh/___DEV/___Private/xyz.webdevs.www/___dist/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#2 /Users/dh/___DEV/___Private/xyz.webdevs.www/___dist/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#3 /Users/dh/___DEV/___Private/xyz.webdevs.www/___dist/vendor/craftcms/cms/src/web/Controller.php(74): charliedev\blockonomicon\controllers\SettingsController->runAction()
#4 /Users/dh/___DEV/___Private/xyz.webdevs.www/___dist/vendor/yiisoft/yii2/base/Module.php(528): charliedev\blockonomicon\controllers\SettingsController->runAction()
#5 /Users/dh/___DEV/___Private/xyz.webdevs.www/___dist/vendor/craftcms/cms/src/web/Application.php(237): craft\web\Application->runAction()
#6 /Users/dh/___DEV/___Private/xyz.webdevs.www/___dist/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#7 /Users/dh/___DEV/___Private/xyz.webdevs.www/___dist/vendor/craftcms/cms/src/web/Application.php(226): craft\web\Application->handleRequest()
#8 /Users/dh/___DEV/___Private/xyz.webdevs.www/___dist/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#9 /Users/dh/___DEV/___Private/xyz.webdevs.www/___dist/web/index.php(22): craft\web\Application->run()
#10 /Users/dh/.composer/vendor/laravel/valet/server.php(133): ::unknown()
#11 {main}
```

**Comment by davidhellmann** [comment]
And don't know whats wrong here :)
![image](https://user-images.githubusercontent.com/764292/36940460-844849e8-1f43-11e8-8f6a-eef4a9a0317b.png)

**Comment by davidhellmann** [comment]
Looks like to clean the Storage Folder Fix the Problem. hm :)

**Comment by davidhellmann** [comment]
Or maybe not. Some Blocks are not exportable :/
![image](https://user-images.githubusercontent.com/764292/36940540-16a6a5f4-1f45-11e8-86ec-d4a9828269f4.png)

Sorry for updates :D

**Comment by sbossarte** [comment]
@davidhellmann To help diagnose this issue, could you please tell me if the blocks that cannot be exported have any fields in them that come from other plugins, and if so, what plugins they are?

Additionally, when migrating it to another machine with a database dump, was the `storage/blockonomicon` folder also migrated?

**Comment by davidhellmann** [comment]
The storage folder was not migrated. I send you later a plugin list but the two above are have no third party. fields inside.

**Comment by sbossarte** [comment]
Some testing has shown that the storage folder missing is the most likely the cause of this. I will add in some additional capabilities to recover from a missing folder.

Also, I'll add warning that it had been removed/missing, because Blockonomicon stores exported data for later use there, and removing it will inhibit the plugin's templating capabilities.

**Comment by sbossarte** [comment]
1.0.1 should better handle missing folders now, and recreate any that happen to be missing.

For the time being, there is no warning about this behavior, but that is in the works for a future release.

**Comment by davidhellmann** [comment]
Looks good! Thanks!
