### ISSUE TITLE
Deprecated .first() call in SettingsController

### ISSUE THREAD

**Issue by juresrpcic** [charliedevelopment/craft3-blockonomicon#2]
Just a small cosmetic issue:

There's a `.first()` used in
```\vendor\charliedev\blockonomicon\src\controllers\SettingsController.php:647```
... it should be `.one()`. It gets logged in Craft CP deprecation errors section.

**Comment by sbossarte** [comment]
Thanks for the find, wonder how that one made it through. Will get it patched up soon.
