### ISSUE TITLE
Error exporting field when using custom path in config

### ISSUE THREAD

**Issue by juresrpcic** [charliedevelopment/craft3-blockonomicon#3]
I tried setting a custom path in `blockonomicon.php` config file. I made sure the path works (it's pulling from .env) - installing example content etc. properly generates in the config-defined folder.

This is set in config:
`'blockStorage' => getenv('CRAFTENV_BASE_PATH_ROOT').'templates/blocks',`

This is how it looks in CP (don't mind those slashes, it's a windows thing but works fine)
**Block Storage Path** `C:\web\crafttest\templates/blocks`

Now when I try to export a dead-simple Matrix field (with just one block type - `text`, with `text` textfield field), I get this error:

http://crafttest.local/index.php?p=admin/actions/blockonomicon/settings/export-block
500 error
{"error":"Unable to find the template “blockonomicon_storage/base.css”."}

Afterwards, this is how the CP looks like:

![craft](https://user-images.githubusercontent.com/2803433/36987481-b80b8d62-209c-11e8-9a7a-5cf04143e5ae.png)

If I try the same thing without setting the config variable but using default `/storage` location, this works fine. It still goes to `http://crafttest.local/admin/blockonomicon/matrix/1` but properly returns the page, the field is green and properly exported.

**Comment by sbossarte** [comment]
Spotted the underlying issue, thank you for the report.

This will be fixed in 1.0.1, which will be pushed as soon as we finish review here.
