### ISSUE TITLE
Add .gitignore to storage\blockonomicon for importoptions.json

### ISSUE THREAD

**Issue by juresrpcic** [charliedevelopment/craft3-blockonomicon#4]
I assume the file `storage\blockonomicon\importoptions.json` server as a quick cache for environment-specific / local import options - ie. setting which asset volume to choose when importing a block with an asset field etc.

It also gets changed when importing/exporting fields in CP and crowds git commits.

I suggest adding `storage\blockonomicon\.gitignore` on install with the following contents:
```
importoptions.json
!.gitignore
```

If there's a good reason to commit this file to git, I'd be happy to know though.

**Comment by sbossarte** [comment]
This will be incorporated in the next version.

**Comment by sbossarte** [comment]
Now in the current version. Thanks for your patience.
